// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// PuffinListerExpansion allows custom methods to be added to
// PuffinLister.
type PuffinListerExpansion interface{}

// PuffinNamespaceListerExpansion allows custom methods to be added to
// PuffinNamespaceLister.
type PuffinNamespaceListerExpansion interface{}
