// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/heptio/tgik/episodes/040/live/pkg/client/clientset/versioned/typed/birds/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeBirdsV1beta1 struct {
	*testing.Fake
}

func (c *FakeBirdsV1beta1) Puffins(namespace string) v1beta1.PuffinInterface {
	return &FakePuffins{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeBirdsV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
