// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/heptio/tgik/episodes/040/live/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Puffins returns a PuffinInformer.
	Puffins() PuffinInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Puffins returns a PuffinInformer.
func (v *version) Puffins() PuffinInformer {
	return &puffinInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
