// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	birds_v1beta1 "github.com/heptio/tgik/episodes/040/live/pkg/apis/birds/v1beta1"
	versioned "github.com/heptio/tgik/episodes/040/live/pkg/client/clientset/versioned"
	internalinterfaces "github.com/heptio/tgik/episodes/040/live/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/heptio/tgik/episodes/040/live/pkg/client/listers/birds/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PuffinInformer provides access to a shared informer and lister for
// Puffins.
type PuffinInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.PuffinLister
}

type puffinInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPuffinInformer constructs a new informer for Puffin type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPuffinInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPuffinInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPuffinInformer constructs a new informer for Puffin type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPuffinInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BirdsV1beta1().Puffins(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BirdsV1beta1().Puffins(namespace).Watch(options)
			},
		},
		&birds_v1beta1.Puffin{},
		resyncPeriod,
		indexers,
	)
}

func (f *puffinInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPuffinInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *puffinInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&birds_v1beta1.Puffin{}, f.defaultInformer)
}

func (f *puffinInformer) Lister() v1beta1.PuffinLister {
	return v1beta1.NewPuffinLister(f.Informer().GetIndexer())
}
