// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/heptio/tgik/episodes/040/live/pkg/apis/birds/v1beta1"
	scheme "github.com/heptio/tgik/episodes/040/live/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PuffinsGetter has a method to return a PuffinInterface.
// A group's client should implement this interface.
type PuffinsGetter interface {
	Puffins(namespace string) PuffinInterface
}

// PuffinInterface has methods to work with Puffin resources.
type PuffinInterface interface {
	Create(*v1beta1.Puffin) (*v1beta1.Puffin, error)
	Update(*v1beta1.Puffin) (*v1beta1.Puffin, error)
	UpdateStatus(*v1beta1.Puffin) (*v1beta1.Puffin, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.Puffin, error)
	List(opts v1.ListOptions) (*v1beta1.PuffinList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Puffin, err error)
	PuffinExpansion
}

// puffins implements PuffinInterface
type puffins struct {
	client rest.Interface
	ns     string
}

// newPuffins returns a Puffins
func newPuffins(c *BirdsV1beta1Client, namespace string) *puffins {
	return &puffins{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the puffin, and returns the corresponding puffin object, and an error if there is any.
func (c *puffins) Get(name string, options v1.GetOptions) (result *v1beta1.Puffin, err error) {
	result = &v1beta1.Puffin{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("puffins").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Puffins that match those selectors.
func (c *puffins) List(opts v1.ListOptions) (result *v1beta1.PuffinList, err error) {
	result = &v1beta1.PuffinList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("puffins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested puffins.
func (c *puffins) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("puffins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a puffin and creates it.  Returns the server's representation of the puffin, and an error, if there is any.
func (c *puffins) Create(puffin *v1beta1.Puffin) (result *v1beta1.Puffin, err error) {
	result = &v1beta1.Puffin{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("puffins").
		Body(puffin).
		Do().
		Into(result)
	return
}

// Update takes the representation of a puffin and updates it. Returns the server's representation of the puffin, and an error, if there is any.
func (c *puffins) Update(puffin *v1beta1.Puffin) (result *v1beta1.Puffin, err error) {
	result = &v1beta1.Puffin{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("puffins").
		Name(puffin.Name).
		Body(puffin).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *puffins) UpdateStatus(puffin *v1beta1.Puffin) (result *v1beta1.Puffin, err error) {
	result = &v1beta1.Puffin{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("puffins").
		Name(puffin.Name).
		SubResource("status").
		Body(puffin).
		Do().
		Into(result)
	return
}

// Delete takes name of the puffin and deletes it. Returns an error if one occurs.
func (c *puffins) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("puffins").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *puffins) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("puffins").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched puffin.
func (c *puffins) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Puffin, err error) {
	result = &v1beta1.Puffin{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("puffins").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
